### ISSUE TITLE
Hangs and prints "main-loop: WARNING: I/O thread spun for 1000 iterations"

### ISSUE THREAD

**Issue by manuelafm** [riscv/riscv-qemu#3] opened 2015-01-17 18:33 UTC
With riscv-qemu from commit bfd1ee736ffbcc137ede0f29e99baa25c49b0842 (29th of Dec of 2014) and using the kernel currently provided as a download from the website (version 3.14.15-g4073e84-dirty (skarandikar@a8)), the emulation seems to stop after printing this message:
```
main-loop: WARNING: I/O thread spun for 1000 iterations
```

Sometimes it happens very early, other times takes hours before this happens.

When that happens, I am able to quit with "ctrl-a x", but not to cancel running programs with "ctrl-c" nor to type new commands if this happens at the shell prompt.

This is possibly a bug in riscv-linux instead of riscv-qemu.  Sadly I cannot provide any useful information, except possibly a backtrace of qemu-system-riscv when this happens, if you think that it's useful.

**Comment by NCommander** [comment] 2015-02-16 01:50
I can confirm this behavior, it seems related to heavy net I/O for me.

**Comment by NCommander** [comment] 2015-02-16 02:07
I applied this patch: http://comments.gmane.org/gmane.comp.emulators.qemu/236931 manually to the QEMU source tree and rebuild. This seems to allow it to get past the deadlock, you'll get the I/O blocking messages occassionally, but after a delay, QEMU will recover and continue where it left off. Seems to be an OK workaround for now, I was able to native-compile gmake using this w/ a NFS root.

**Comment by NCommander** [comment] 2015-02-16 03:36
Ok, I wasn't 100% right on that being a fix. The issue appears to be coming from something setting a blocking I/O, which seems to become a non-blocking I/O which causes the mutexs to deadlock. My attempts to add debugging printfs seem to have "fixed" the problem from occuring so trying to debug this is stalled ...

**Comment by lambdafu** [comment] 2015-03-04 21:12
+1.  this is a real show stopper.

**Comment by NCommander** [comment] 2015-03-05 03:04
Eek, I forgot to post I found a workaround. If you force everything to be blocking, the issue goes away, you have to set a variable in the main loop which controls blocking.

In vl.c:

Find:

        nonblocking = !kvm_enabled() && !xen_enabled() && last_io > 0;

and set it to 0. 

I think. It might be one. I don't have my machine handy to verify which value fixes it. Performance takes a bit of a dive but it works; I was able to native build GCC like this.

**Comment by lambdafu** [comment] 2015-03-05 22:38
yeah, that helps a lot! thanks!

**Comment by sagark** [comment] 2016-02-11 05:34
Closing this since I haven't seen it happen with the privileged update + rebase. Let me know if it reappears.

**Closed by sagark** 2016-02-11 05:34 UTC

**Comment by visbits** [comment] 2016-04-17 00:55
Seeing this currently.

root@osc-1011.prd > rpm -qa | grep qemu
qemu-kvm-1.5.3-105.el7_2.3.x86_64
qemu-kvm-common-1.5.3-105.el7_2.3.x86_64
qemu-img-1.5.3-105.el7_2.3.x86_64
libvirt-daemon-driver-qemu-1.2.17-13.el7_2.4.x86_64
ipxe-roms-qemu-20130517-7.gitc4bce43.el7.noarch
root@osc-1011.prd.cin1.corp.beyondhosting.net > rpm -qa | grep libvirt
libvirt-client-1.2.17-13.el7_2.4.x86_64
libvirt-daemon-driver-storage-1.2.17-13.el7_2.4.x86_64
libvirt-python-1.2.17-2.el7.x86_64
libvirt-daemon-driver-nodedev-1.2.17-13.el7_2.4.x86_64
libvirt-daemon-driver-network-1.2.17-13.el7_2.4.x86_64
libvirt-daemon-driver-interface-1.2.17-13.el7_2.4.x86_64
libvirt-daemon-driver-qemu-1.2.17-13.el7_2.4.x86_64
libvirt-daemon-driver-nwfilter-1.2.17-13.el7_2.4.x86_64
libvirt-daemon-driver-secret-1.2.17-13.el7_2.4.x86_64
libvirt-daemon-1.2.17-13.el7_2.4.x86_64
libvirt-daemon-kvm-1.2.17-13.el7_2.4.x86_64  

Linux osc-1011.prd 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by marmistrz** [comment] 2017-04-07 14:11
I experience the same while running Minix under Arch Linux, qemu 1.8.0

**Comment by specing** [comment] 2017-07-19 14:52
While I am not using riscv-qemu, I have this exact issue only when qemu is configured with 2 network interface cards, with one the above does not occur.
